use_frameworks!
platform :ios, '10.0'

target 'SinkEmAll_Example' do
  pod 'SinkEmAll', :path => '../'

  target 'SinkEmAll_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'RxNimble'
  end
end
